### ISSUE TITLE
Controls.Filters

### ISSUE THREAD

**Issue by chesdenis** [chesdenis/Personal-File-Storage#30]
- [x] Создаем ветку features-controls-filters
- [x] Публикуем ветку features-controls-filters
- [x] Смотрим [поясняющий материал](https://www.youtube.com/watch?v=pTh0KCuFGqM)
- [x] Смотрим [доп. инф.](https://youtu.be/FArvHcPY2kQ)
- [x] Создаем контрол (ы)
- [x] Делаем комит(ы) [доп. инф.](https://www.youtube.com/watch?v=PBS19eiDqhc)
- [x] Синхронизируемся с GitHub
- [x] Создаем MergeRequest

**Comment by NomerovskiySergey** [comment]
Done
