### ISSUE TITLE
ImagesGroupPreview.AnimatedBox

### ISSUE THREAD

**Issue by chesdenis** [chesdenis/Personal-File-Storage#42]

**Comment by ivanblindyuk** [comment]
Напомните, пожалуйста, изначальную идею этого контрола. Изображения должны анимироваться по наведению курсора или непрерывно друг за другом в каком-нибудь случайном порядке?

**Comment by chesdenis** [comment]
Я думаю непрерывно друг за другом. Примерно как плитки контактов в WinPhone. Очень хороший пример - [можно посмотреть тут](http://tympanus.net/Development/AnimatedResponsiveImageGrid/)
