### ISSUE TITLE
ImagePreview.Placeholders

### ISSUE THREAD

**Issue by chesdenis** [chesdenis/Personal-File-Storage#60]
Применить https://placehold.it/ к контролу, для возможности использования без сервисов получения изображения

**Comment by ivanblindyuk** [comment]
Так получилось, что я это сделал в процессе выполнения Issue #42. Поэтому это попало в ветку  features-controls-imagesgrouppreview-animated

**Comment by chesdenis** [comment]
> Так получилось, что я это сделал в процессе выполнения Issue #42. Поэтому это попало в ветку features-controls-imagesgrouppreview-animated

ок, я думаю все равно сольется с develop так или иначе.
