### ISSUE TITLE
Modules.Books

### ISSUE THREAD

**Issue by chesdenis** [chesdenis/Personal-File-Storage#62]
- [x] Создать отдельный модуль аналогично модулю https://github.com/chesdenis/Personal-File-Storage/blob/develop/PFS.Server.MvcApp/App/Components/Photos/photos.module.ts.
- [x] Настроить роутинг в файле модуля
- [x] Добавить компоненты для различных режимов (Default, Tags, Dates)

**Comment by NomerovskiySergey** [comment]
App\Components\Books\books.module.ts(35,9): error TS2304: Cannot find name 'ByAlbumsComponent'.
App\Components\Books\books.module.ts(37,9): error TS2304: Cannot find name 'ByPlacesComponent'.

При buildде вот такие ошибки вылазят, не могу понять откуда он их тянет

**Comment by NomerovskiySergey** [comment]
Вопрос закрыт=)
